### ISSUE TITLE
Server cmds are not documented anywhere

### ISSUE THREAD

**Issue by cob16** [Arie/serveme#17]
I know there [here](https://github.com/Arie/serveme/blob/master/app/workers/log_worker.rb#L7) but others might not want to search the code for such a thing

Perhaps an addition to the 
- [x]  README.md
- [x] wiki
- [x] - Fnq page on the website
- [x] - ~~current cmds could even include a "!help cmd"~~ (would conflict with other plugins)

BTW i am happy to make a pull request or format up a wiki myself etc just looking for your thoughts first :smile:

**Comment by Arie** [comment]
PRs are always welcome :)

**Comment by cob16** [comment]
Ok i wrote i litte page for the commands to live in and expanded out the rest of the readme into the wiki

**Comment by Arie** [comment]
Sorry for my late response, I just noticed your changes are already live in the wiki, thank you very much <3

**Comment by cob16** [comment]
#18

**Comment by cob16** [comment]
this issue can be closed now
