### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BenjaminSchaaf** [Arie/serveme#22]
Is this project under an open source license?

**Comment by Arie** [comment]
Yep, Apache, added it just now ;)

**Comment by BenjaminSchaaf** [comment]
Thanks,
Just to follow up, `Copyright {yyyy} {name of copyright owner}` should probably be filled in.

**Comment by Arie** [comment]
Hehe, cheers. Github did do that automatically for MIT, but not for Apache. Thanks :)
