### ISSUE TITLE
Update the README for contributors

### ISSUE THREAD

**Issue by cob16** [Arie/serveme#23]
There seems to have been quite a few changes since the readme was last written. Im trying to get a dev instance going but the readme isn't helping (for example serveme seems to be using redis now not memcached)

Any tips on a minimal install would also be good i.e. no cron jobs, steam API keys speaking of which the initializers file is completely ignored so there is no idea what sould be there other than the var declaration

**Comment by Arie** [comment]
I'll have to try and install on a fresh box to update the instructions. 

Redis is used for sidekiq jobs, memcached is used for caching and global locking.

**Comment by cob16** [comment]
Ok ill hold off for now. Any reason not to do redis for the cashing too? https://stackoverflow.com/questions/10558465/memcached-vs-redis

**Comment by Arie** [comment]
I was already using memcached and didn't want to set up an extra redis server for caching.
