### ISSUE TITLE
!who command should return current steam name

### ISSUE THREAD

**Issue by cob16** [Arie/serveme#24]
Users expect the who command to bring back the current users name. Currently it brings back the name that was used when logging in to serveme this could be for considerably long ago. 

One possible solution would be to do a lookup when a reservation is made.

**Comment by Arie** [comment]
Yeah good idea, should probably fire off a sidekiq worker to query the current steam name when a reservation is made. Or maybe a daily job to update the nicknames.

**Comment by cob16** [comment]
Yeah your first suggestion sounds like a good idea as that would likely be when we actually need it. Im not sure the second is viable as if we get past [10,000 steam accounts steam cuts us off](https://steamcommunity.com/dev/apiterms) (unless you are special and valve let you).
