### ISSUE TITLE
API for GETing reservations?

### ISSUE THREAD

**Issue by cob16** [Arie/serveme#28]
I am making a [mumble bot for comp tf/souce games](https://github.com/cob16/go-butler) and one of the things i want it to do is do cool things with connect strings ect. My idea would for the user to give a reservation id and the bot returns connect info when the reservation starts ect ect.

Esentially an APi for [http://serveme.tf/recent-reservations](http://serveme.tf/recent-reservations) would be good. Only public info would be shown.

**Comment by Arie** [comment]
Well the connect string isn't public info ofc ;)

**Comment by cob16** [comment]
Failing that then :P. An APi that auths as the user for the info

**Comment by Arie** [comment]
Fixed in 00425fe20593f8520efdb32fe885cfcb37dfc2e8

**Comment by cob16** [comment]
I’m getting blank white screen when going to these URLs. Not a 404 or anything

**Comment by Arie** [comment]
Use a valid API key

**Comment by cob16** [comment]
Ah that would explain why it is disabled in my settings page 🤦‍.
