### ISSUE TITLE
Move to HTTPS

### ISSUE THREAD

**Issue by cob16** [Arie/serveme#30]
OK really not critical due to the nature of the site, but its 2017 and we have [letsencrypt](https://letsencrypt.org/) for free certs nowadays.

**Comment by Arie** [comment]
https://serveme.tf, https://na.serveme.tf, https://csgo.serveme.tf

**Comment by cob16** [comment]
Ah you offer http also I see

**Comment by Arie** [comment]
I had an issue before with the steam login callback failing when operating exclusively in HTTPS mode. Will check if that's still a problem, and if not, force HTTPS.

**Comment by Arie** [comment]
Forcing SSL
