### ISSUE TITLE
How can i change War Mod BFG and put e-bot? [Sorry if wrong thread]

### ISSUE THREAD

**Issue by Mikolajek451YT** [Arie/serveme#34]
Hello! how can i disable war mod BFG setting? and ofc place e-bot because i checked and ebot can get in the server but war mod bfg is kinda bad for managing the games and ebot is bugging when this is on. Thank you for answering if someone will do.

**Comment by Arie** [comment]
You can disable warmod with:
`rcon wm_active 0` or unload the plugin entirely with `rcon sm plugins unload warmod`.

**Comment by Mikolajek451YT** [comment]
Thank you bro.
