### ISSUE TITLE
Increase sv_quota_stringcmdspersecond in config.

### ISSUE THREAD

**Issue by icewind1991** [Arie/serveme#38]
The default `sv_quota_stringcmdspersecond` of 40 is really easy to hit on accident with anything that is bound to scrollwheel, setting it to something like 200 will prevent most accident triggering of it while still providing protection against command spamming

**Comment by Arie** [comment]
Thank you, done!

**Comment by icewind1991** [comment]
This change seems to no longer be applied properly. It it back the default value of 40

**Comment by Arie** [comment]
Just checked a couple of reservations, and it does seem to still apply:
```
"sv_quota_stringcmdspersecond" = "200" ( def. "40" )
 - How many string commands per second clients are allowed to submit, 0 to disallow all string commands
 ```

**Comment by icewind1991** [comment]
Hmm, when I test it now it does indeed work correctly. Not sure why it wasn't working 2 days ago...
