### ISSUE TITLE
Use player IP information to make ping predictions

### ISSUE THREAD

**Issue by Arie** [Arie/serveme#39]
Rank servers, show average pings by players on the same ISPs to servers....

**Comment by cob16** [comment]
One alternative solution could be to do a TCP ping on the server using a client-side library like this one -> https://www.npmjs.com/package/@network-utils/tcp-ping 

Does this feature need to be server side for any reason?

**Comment by Arie** [comment]
We want to tell the player what their expected ping will be to a server. We can't reliably ping a player IP from a server (CG-NAT, NAT, firewalls, etc..), and we can't run code on any of the NA tragicservers for example.

I'm unlikely to implement this issue anymore, I don't think it will be worth the effort.
