### ISSUE TITLE
Admin interface to mass upload maps, configs, plugins, and whitelists

### ISSUE THREAD

**Issue by Arie** [Arie/serveme#40]
Should accept a zipfile the contents of which will be extracted to the `tf` dir of every server. For SSH based servers this can be done by unzipping remotely, but FTP based servers will need to have the files sent over after unzipping on the serveme-side.

From the zip file, new configs and whitelists should be found and added to the serveme database.

**Comment by cob16** [comment]
To questions to clarify

- are how are new maps and whitelists currently propagated? (bash script?) 
- How often is this done? (just to init the server or this to be done periodically?)
- Is it worth breaking these uploads down to individual folders i.e maps etc? 
- How approprate would configuration management be (i.e ansable) to solve this?

**Comment by Arie** [comment]
1. Bash script that calls rsync
2. Manually whenever there are new or updated configs
3. There are separate scripts for config and map syncing already, that's sufficiently broken down I feel
4. I don't know enough about ansible to give an answer. But I think a tool like ansible is a good way to do the initial setup of servers, perhaps keeping them up to date too. TF2 servers auto-update for the most part so they're fairly low maintenance.
